version: '3'

services:
  microblog:
    image: registry.gitlab.com/abeliam/microblog
    depends_on:
      - database
    networks:
      - microblog

  database:
    image: mongo
    networks:
      - microblog

networks:
  microblog:
